-- Lua generated by binding.py
local m = {}

---@param scene number
---@return nil
m.transitionTo = function(scene)
	cpp_transitionTo(scene)
end

---@return nil
m.exit = function()
	cpp_exit()
end


return m