-- Lua generated by binding.py
local m = {}

---@param file string
---@return number
m.loadTexture = function(file)
	return cpp_loadTexture(file)
end

---@param textureHandle number
---@return nil
m.unloadTexture = function(textureHandle)
	cpp_unloadTexture(textureHandle)
end

---@param textureHandle int
---@param pos Vector2
---@param size Vector2
---@return nil
m.drawTexture = function(textureHandle,pos,size)
	cpp_drawTexture(textureHandle,pos,size)
end

---@param textureHandle int
---@return Vector2
m.getTextureSize = function(textureHandle)
	return cpp_getTextureSize(textureHandle)
end


return m