-- Lua generated by binding.py
local m = {}

m.info = function(info)
    cpp_info(tostring(info))
end

m.error = function(error)
    cpp_error(tostring(error))
end

m.warning = function(warning)
    cpp_warning(tostring(warning))
end

---@param t table
---@return table A shallow copy of t
m.shallowCopyTable = function(t)
    local tt = {}

    for k, v in pairs(t) do
        tt[k] = v
    end

    return tt
end

---@param t1 table
---@param t2 table
---@return table
---Merges 2 tables, uses t1 as the base and overrides anything in t1 with t2
m.mergeTables = function(t1, t2)
    local t = m.shallowCopyTable(t1)

    for k, v in pairs(t2) do
        if type(t[k]) == "table" and type(t2[k]) == "table" then
            t[k] = m.mergeTables(t[k], t2[k])
        else
            t[k] = v
        end
    end

    return t
end

---@generic T
---@param t table
---@param key string | number
---@param default T
---@return T
m.getOr = function(t, key, default)
    local val = t[key]

    if val == nil then
        return default
    end

    return val
end
---@return number
m.getScreenWidth = function()
	return cpp_getScreenWidth()
end

---@return number
m.getScreenHeight = function()
	return cpp_getScreenHeight()
end

---@param text string
---@param fontSize number
---@return Vector2
m.measureText = function(text,fontSize)
	return cpp_measureText(text,fontSize)
end

---@param size Vector2
---@param totalSize Vector2
---@return Vector2
m.getCenter = function(size,totalSize)
	return cpp_getCenter(size,totalSize)
end

---@param x Vector2
---@param pos Vector2
---@param size Vector2
---@return boolean
m.within = function(x,pos,size)
	return cpp_within(x,pos,size)
end


return m