-- Lua generated by binding.py
local m = {}

m.info = function(info) 
    cpp_info(tostring(info))
end

m.error = function(error)
    cpp_error(tostring(error))
end

m.warning = function(warning)
    cpp_warning(tostring(warning))
end

---@return number
m.getScreenWidth = function()
	cpp_getScreenWidth()
end

---@return number
m.getScreenHeight = function()
	cpp_getScreenHeight()
end

---@param pos Vector2
---@return Vector2
m.anchorTopLeft = function(pos)
	cpp_anchorTopLeft(pos)
end

---@param pos Vector2
---@return Vector2
m.anchorTopRight = function(pos)
	cpp_anchorTopRight(pos)
end

---@param pos Vector2
---@return Vector2
m.anchorBtmLeft = function(pos)
	cpp_anchorBtmLeft(pos)
end

---@param pos Vector2
---@return Vector2
m.anchorBtmRight = function(pos)
	cpp_anchorBtmRight(pos)
end

---@param text string
---@param fontSize number
---@param pos Vector2
---@param color Color
---@return Vector2
m.drawText = function(text,fontSize,pos,color)
	cpp_drawText(text,fontSize,pos,color)
end

---@param text string
---@param fontSize number
---@return Vector2
m.measureText = function(text,fontSize)
	cpp_measureText(text,fontSize)
end

---@param size Vector2
---@param totalSize Vector2
---@return Vector2
m.getCenter = function(size,totalSize)
	cpp_getCenter(size,totalSize)
end

---@param x Vector2
---@param pos Vector2
---@param size Vector2
---@return boolean
m.within = function(x,pos,size)
	cpp_within(x,pos,size)
end


return m