-- Lua generated by binding.py
local m = {}

m.info = function(info) 
    cpp_info(tostring(info))
end

m.error = function(error)
    cpp_error(tostring(error))
end

m.warning = function(warning)
    cpp_warning(tostring(warning))
end

---@return number
m.getScreenWidth = function()
	cpp_getScreenWidth()
end

---@return number
m.getScreenHeight = function()
	cpp_getScreenHeight()
end

---@param text string
---@param fontSize number
---@return Vector2
m.measureText = function(text,fontSize)
	cpp_measureText(text,fontSize)
end

---@param size Vector2
---@param totalSize Vector2
---@return Vector2
m.getCenter = function(size,totalSize)
	cpp_getCenter(size,totalSize)
end

---@param x Vector2
---@param pos Vector2
---@param size Vector2
---@return boolean
m.within = function(x,pos,size)
	cpp_within(x,pos,size)
end


return m